repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.14.0
  hooks:
    - id: commitizen
      stages: [commit-msg]

# Stop commits to master
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0  # Use the ref you want to point at
  hooks:
  - id: no-commit-to-branch
    stages: [commit, push]
    args: [--branch, master]  
  - id: check-merge-conflict
    stages: [commit, push]

- repo: https://github.com/outcome-co/action-check-todos
  rev: v1.5.0
  hooks:
  - id: check-todos
    args: ['--ignore','coverage','**/*']
    stages: [push]

- repo: local
  hooks:

  - id: check_pre_commit_version
    name: Check pre-commit version
    stages: [push]
    verbose: true
    pass_filenames: false
    language: system
    # Must have at least 2.5.0 running
    entry: sh -c "test ${PRE_COMMIT:-0} -eq 1"

  - id: checks
    name: Checks
    language: system  # Running on the local system
    stages: [push]
    verbose: true
    entry: make check
    types: [file, python]  # Only triggered if python files are changed in the commit
    pass_filenames: false

  - id: test
    name: Tests
    language: system  # Running on the local system
    stages: [push]
    verbose: true
    entry: make test-unit
    types: [file, python]  # Only triggered if python files are changed in the commit
    pass_filenames: false
